/*Consulta no banco de dados para trazer a relação dos usuários ativos associados, vinculados as unidades/setores
da Secretária Municipal da Educação de Ribeirão Preto*/
SELECT A.CDUSUARIO, U.NMUSUARIO, B.SGORGAOSETOR, A.FLSETORDEFAULT
FROM SOLAR.ESEGUSRSETORSIST A
JOIN SOLAR.ECPAORGAOSETOR B ON A.CDORGAOSETOR = B.CDORGAOSETOR
JOIN SOLAR.ESEGUSUARIO U ON A.CDUSUARIO = U.CDUSUARIO
WHERE A.CDSISTEMA = 64
AND (B.SGORGAOSETOR LIKE '%EDUC%' OR B.SGORGAOSETOR LIKE '%DIR%')
AND B.FLSETORATIVO = 'S'
ORDER BY A.CDUSUARIO;

/*Consulta no banco de dados para trazer a relação dos usuários ativos associados, vinculados as unidades/setores
da Secretária Municipal da Assistência Social de Ribeirão Preto*/
SELECT A.CDUSUARIO AS Usuário, 
       INITCAP(U.NMUSUARIO) AS Nome_do_Usuário, 
       B.SGORGAOSETOR AS Sigla_da_Unidade_Setor, 
       CASE WHEN A.FLSETORDEFAULT = 'S' THEN 'Sim'
            WHEN A.FLSETORDEFAULT = 'N' THEN 'Não'
            ELSE A.FLSETORDEFAULT 
       END AS Unidade_Setor_Padrão
FROM SOLAR.ESEGUSRSETORSIST A
JOIN SOLAR.ECPAORGAOSETOR B ON A.CDORGAOSETOR = B.CDORGAOSETOR
JOIN SOLAR.ESEGUSUARIO U ON A.CDUSUARIO = U.CDUSUARIO
WHERE A.CDSISTEMA = 64
AND (B.SGORGAOSETOR LIKE '%SEMAS%' OR B.SGORGAOSETOR LIKE '%FRASSOL%' OR B.SGORGAOSETOR LIKE '%PAEFI%' OR B.SGORGAOSETOR LIKE '%MJM%')
AND B.FLSETORATIVO = 'S'
ORDER BY U.NMUSUARIO;

/*Consulta no banco de dados para trazer a relação das unidades/setores do usuário informado*/
SELECT
    A.CDUSUARIO AS Usuário,
    U.NMUSUARIO AS Nome_do_Usuário,
    B.SGORGAOSETOR AS Sigla_da_Unidade_Setor,
    B.NMORGAOSETOR AS Nome_da_Unidade_Setor,
    A.FLSETORDEFAULT AS Unidade_Setor_Padrão
FROM SOLAR.ESEGUSRSETORSIST A
JOIN SOLAR.ECPAORGAOSETOR B ON A.CDORGAOSETOR = B.CDORGAOSETOR
JOIN SOLAR.ESEGUSUARIO U ON A.CDUSUARIO = U.CDUSUARIO
WHERE A.CDSISTEMA = 64
AND A.CDUSUARIO = '36460043809' --ERICK MARZOLA BRESCIANI--
ORDER BY CASE 
            WHEN A.FLSETORDEFAULT = 'S' THEN 1 
            ELSE 2 
         END, 
         B.SGORGAOSETOR;

--Consulta no banco de dados para trazer a relação dos usuários ativos--
SELECT CDUSUARIO, NMUSUARIO, DTATIVACAO, TPUSUARIO, NUCPFCNPJ, FLHABILITADO, DEEMAIL, DTULTLOGINOK, TPPESSOA
FROM SOLAR.ESEGUSUARIO WHERE FLHABILITADO = 'S' ORDER BY NMUSUARIO;


--Busca todos os usuários ativos em setores ativos, retirando portal e buscando por orgao--
SELECT 
    A.CDUSUARIO, 
    U.NMUSUARIO, 
    B.SGORGAOSETOR, 
    B.NMORGAOSETOR ,
    B.FLSETORATIVO ,
    A.FLSETORDEFAULT
FROM 
    SOLAR.ESEGUSRSETORSIST A
    INNER JOIN SOLAR.ECPAORGAOSETOR B ON A.CDORGAOSETOR = B.CDORGAOSETOR
    INNER JOIN SOLAR.ESEGUSUARIO U ON A.CDUSUARIO = U.CDUSUARIO
WHERE 
    A.CDSISTEMA = 64
    AND B.FLSETORATIVO = 'S'
    AND U.FLHABILITADO = 'S'
    AND B.CDORGAOSETOR != 18
    AND B.CDORGAO = 1 -- PMRP
ORDER BY 
    CDUSUARIO


--Busca todos os usuários ativos (sem duplicidade) em setores ativos, retirando portal e buscando por orgao--
SELECT 
    COUNT(DISTINCT A.CDUSUARIO) AS TOTAL_USUARIOS_ATIVOS
FROM 
    SOLAR.ESEGUSRSETORSIST A
    INNER JOIN SOLAR.ECPAORGAOSETOR B ON A.CDORGAOSETOR = B.CDORGAOSETOR
    INNER JOIN SOLAR.ESEGUSUARIO U ON A.CDUSUARIO = U.CDUSUARIO
WHERE 
    A.CDSISTEMA = 64
    AND B.FLSETORATIVO = 'S'
    AND U.FLHABILITADO = 'S'
    AND B.CDORGAOSETOR != 18
    AND B.CDORGAO = 1 -- PMRP

--Busca todos os usuários ativos (sem duplicidade) no setor "PORTAL" (PORTAL) e buscando por orgao--
SELECT 
    COUNT(DISTINCT A.CDUSUARIO) AS TOTAL_USUARIOS_ATIVOS
FROM 
    SOLAR.ESEGUSRSETORSIST A
    INNER JOIN SOLAR.ECPAORGAOSETOR B ON A.CDORGAOSETOR = B.CDORGAOSETOR
    INNER JOIN SOLAR.ESEGUSUARIO U ON A.CDUSUARIO = U.CDUSUARIO
WHERE 
    A.CDSISTEMA = 64
    AND B.FLSETORATIVO = 'S'
    AND U.FLHABILITADO = 'S'
    AND B.CDORGAOSETOR = 18
    AND B.CDORGAO = 1 -- PMRP

--Busca o total de usuários ativos (sem duplicidade) em setores ativos, separando o total de usuários do portal interno e portal externo ("PORTAL" (PORTAL)), buscando por orgao e somando o total de usuários do portal internon + portal externo--
SELECT 
    COUNT(DISTINCT CASE WHEN B.CDORGAOSETOR != 18 THEN A.CDUSUARIO END) AS TOTAL_DE_USUARIOS_ATIVOS_DO_PORTAL_INTERNO,
    COUNT(DISTINCT CASE WHEN B.CDORGAOSETOR = 18 THEN A.CDUSUARIO END) AS TOTAL_DE_USUARIOS_ATIVOS_DO_PORTAL_EXTERNO,
    COUNT(DISTINCT CASE WHEN B.CDORGAOSETOR != 18 THEN A.CDUSUARIO END) + 
    COUNT(DISTINCT CASE WHEN B.CDORGAOSETOR = 18 THEN A.CDUSUARIO END) AS TOTAL_GERAL
FROM 
    SOLAR.ESEGUSRSETORSIST A
    INNER JOIN SOLAR.ECPAORGAOSETOR B ON A.CDORGAOSETOR = B.CDORGAOSETOR
    INNER JOIN SOLAR.ESEGUSUARIO U ON A.CDUSUARIO = U.CDUSUARIO
WHERE 
    A.CDSISTEMA = 64
    AND B.FLSETORATIVO = 'S'
    AND U.FLHABILITADO = 'S'
    AND B.CDORGAO = 1 -- PMRP


/*Consulta no banco de dados para trazer a relação das unidades/setores e suas unidades/setores pai de um órgão*/
SELECT 
    ESPAI.SGORGAOSETOR AS SGORGAOSETOR_PAI, 
    ESPAI.NMORGAOSETOR AS NMORGAOSETOR_PAI,
    ES.SGORGAOSETOR, 
    ES.NMORGAOSETOR
FROM 
    ECPAORGAOSETOR ES
LEFT JOIN 
    ECPAORGAOSETOR ESPAI ON ES.CDSETORPAI = ESPAI.CDORGAOSETOR
WHERE 
    ES.CDORGAO = (SELECT CDORGAOSETOR FROM ECPAORGAOSETOR WHERE SGORGAOSETOR = 'PMRP')-- orgao
    AND ES.FLSETORATIVO = 'S'
   -- AND ES.SGORGAOSETOR = 'ADM-PCCS ANALISADOS'
ORDER BY 
    ESPAI.SGORGAOSETOR;